name: Run Automation Tests

on:
  workflow_call:

permissions:
  contents: read


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print starting test
        run: echo "Automation tests running from Repo2!"

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run dummy test
        run: |
          echo "Running dummy test..."
          sleep 2
          echo "Test completed!"

  test2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo2
        uses: actions/checkout@v4

      - name: List files to verify checkout
        run: ls -R .

      - name: Print Python version
        run: python3 --version

      - name: Run Python file
        run: python3 myp.py
